apiVersion: v1
kind: Service
metadata:
  name: proposal-generator-service
spec:
  selector:
    app: proposal-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer